[default]
DEBUG = false
FLASK_ADMIN_NAME = "OpenTelemetry Admin"
FLASK_ADMIN_TEMPLATE_MODE = "bootstrap3"
FLASK_ADMIN_SWATCH = 'cerulean'
SQLALCHEMY_DATABASE_URI = '@format {env[SQLALCHEMY_DATABASE_URI]}'
SIMPLELOGIN_LOGOUT_URL='/logout/'
TITLE = "OpenTelemetry"
SECRET_KEY = '@format {env[SECRET_KEY]}'
PASSWORD_SCHEMES = ['pbkdf2_sha512', 'md5_crypt']
EXTENSIONS = [
    "src.flaskr.ext.appearance:init_app",
    "src.flaskr.ext.database:init_app",
    "src.flaskr.ext.auth:init_app",
    "src.flaskr.ext.admin:init_app",
    "src.flaskr.ext.commands:init_app",
    "src.flaskr.ext.opentelemetry:init_app",

    "src.flaskr.blueprints.restapi:init_app",
    "src.flaskr.blueprints.dash:init_app",
]


[development]
EXTENSIONS = [
    "flask_debugtoolbar:DebugToolbarExtension",
    "dynaconf_merge_unique"  # to reuse extensions list from [default]
]
TEMPLATES_AUTO_RELOAD = true
DEBUG = true
DEBUG_TOOLBAR_ENABLED = true
DEBUG_TB_INTERCEPT_REDIRECTS = false
DEBUG_TB_PROFILER_ENABLED = true
DEBUG_TB_TEMPLATE_EDITOR_ENABLED = true
DEBUG_TB_PANELS = [
    "flask_debugtoolbar.panels.versions.VersionDebugPanel",
    "flask_debugtoolbar.panels.sqlalchemy.SQLAlchemyDebugPanel",
    "flask_debugtoolbar.panels.timer.TimerDebugPanel",
    "flask_debugtoolbar.panels.headers.HeaderDebugPanel",
    "flask_debugtoolbar.panels.request_vars.RequestVarsDebugPanel",
    "flask_debugtoolbar.panels.template.TemplateDebugPanel",
    "flask_debugtoolbar.panels.route_list.RouteListDebugPanel",
    "flask_debugtoolbar.panels.logger.LoggingPanel",
    "flask_debugtoolbar.panels.profiler.ProfilerDebugPanel",
    "flask_debugtoolbar.panels.config_vars.ConfigVarsDebugPanel"
]

[testing]

[production]

[jupyter]
EXTENSIONS = [
    "src.flaskr.ext.database:init_app",
]
