volumes:
  open_telemetry_grafana_storage:
  open_telemetry_promtail_log:

networks:
  open_telemetry:

services:

  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
    networks:
      - open_telemetry

  # Zipkin
  zipkin:
    build: .
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    networks:
      - open_telemetry

  prometheus:
    build: .
    image: prom/prometheus
    volumes:
      - ${PWD}/dev/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090"
    networks:
      - open_telemetry

  loki:
    image: grafana/loki:2.6.0
    ports:
      - "3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - open_telemetry

  promtail:
    image: grafana/promtail:2.6.0
    volumes:
      - open_telemetry_promtail_log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - open_telemetry
    depends_on:
      - loki

  otel-collector:
    build: .
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ${PWD}/dev/otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "55679:55679" # zpages extension
    networks:
      - open_telemetry
    command:
      - "--config=/etc/otel-collector-config.yaml"
    depends_on:
      - jaeger
      - zipkin
      - prometheus
      - loki

  grafana:
    image: grafana/grafana-oss:latest
    volumes:
      - open_telemetry_grafana_storage:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - open_telemetry
